POST http://127.0.0.1:3000/cronograma
Content-Type: application/json

{
    "data": "2025-03-20",
    "materias": ["math","mimi"],
    "dayweek" : ["segunda"],
    "time": 2,
    "sleepstart" : 20,
    "sleepend": 4
}

###

GET  http://127.0.0.1:3000/cronograma

//?search=node filtrar a pesquisa 
//e sem ele é exibido todos os registros

###

PUT http://127.0.0.1:3000/cronograma/38843942-d277-48b1-9ca5-2e69dc5ae4e0
Content-Type: application/json

{
     "data": "2025-03-20",
    "materias": ["math", "dormir"],
    "dayweek" : ["segunda"],
    "time": 2,
    "sleepstart": 20,
    "sleepend": 4
}


###

DELETE http://127.0.0.1:3000/cronograma/38843942-d277-48b1-9ca5-2e69dc5ae4e0